services:
  - type: web
    name: hatch-tracker-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: API_SECRET
        value: Hatches101310
      - key: PYTHON_VERSION
        value: "3.11.0"
    plan: free
